- group_config:

    - wknd-members-actool-example:

       - name: WKND Members AC Tool Example
         isMemberOf: 
         members: 
         path: w

- ace_config:

    - wknd-members-actool-example:

       - path: /content/cq:tags
         permission: allow
         actions: read
         privileges: 

- user_config:

    - wknd-user:

        - name: "WKND User"
          isMemberOf: wkndmembers
          password: wknd-user
          path: /home/users/taradevko/test
          preferencesContent: <jcr:root jcr:primaryType="nt:unstructured" cq.authoring.editor.page.showOnboarding620="false" cq.authoring.editor.page.showOnboarding62="false" granite.shell.showonboarding620="false"/>