- group_config:

    - wknd-members-actool-example:

       - name: WKND Members AC Tool Example
         isMemberOf: 
         members: 
         path: w

- ace_config:

    - wknd-members-actool-example:

       - path: /content/cq:tags
         permission: allow
         actions: read
         privileges: 
